//
// Copyright © 2026 TraceX SAS.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Email wording per language. Kept in code rather than in plugin lang files because the
// transactor registers only English strings for platform plugins.

import { defaultEmailStrings, type EmailStrings } from './content'

const ru: EmailStrings = {
  eventMention: 'Вас упомянули',
  eventReply: 'Новый ответ',
  eventMessage: 'Новое сообщение',
  eventReaction: 'Новая реакция',
  eventUpdate: 'Изменено',
  eventCreate: 'Создано',
  eventAssignment: 'Назначено вам',
  eventRequest: 'Требуется действие',
  titleMention: '{sender} упомянул(а) вас',
  titleReply: '{sender} ответил(а) в {object}',
  titleReplyOwn: '{sender} ответил(а) на ваше сообщение',
  titleMessage: 'Новое сообщение в {object}',
  titleReaction: '{sender} отреагировал(а) {emoji} на ваше сообщение',
  titleUpdate: '{object}: есть изменения',
  titleCreate: '{object}: создано',
  titleAssignment: '{sender} назначил(а) вам {object}',
  titleAssignmentNoSender: 'Вам назначено: {object}',
  titleRequest: 'Требуется действие: {object}',
  quoteOwn: 'Ваше сообщение',
  quoteOther: '{author} пишет',
  quoteAnonymous: 'Исходное сообщение',
  actionReply: 'Ответить в {app}',
  actionOpen: 'Открыть в {app}',
  actionOpenObject: 'Открыть: {class}',
  readMore: 'Полный текст сообщения — в {app}',
  reasonMention: 'Вы получили это письмо, потому что вас упомянули.',
  reasonConversation: 'Вы получили это письмо, потому что подписаны на это обсуждение.',
  reasonObject: 'Вы получили это письмо, потому что подписаны на обновления «{object}».',
  reasonAssignment: 'Вы получили это письмо, потому что вас назначили.',
  reasonRequest: 'Вы получили это письмо, потому что от вас ожидается действие.',
  reasonDefault: 'Вы получили это письмо в соответствии с настройками уведомлений.',
  notificationSettings: 'Настройки уведомлений',
  copyright: '© {app} — Все права защищены'
}

const de: EmailStrings = {
  eventMention: 'Sie wurden erwähnt',
  eventReply: 'Neue Antwort',
  eventMessage: 'Neue Nachricht',
  eventReaction: 'Neue Reaktion',
  eventUpdate: 'Aktualisiert',
  eventCreate: 'Erstellt',
  eventAssignment: 'Ihnen zugewiesen',
  eventRequest: 'Aktion erforderlich',
  titleMention: '{sender} hat Sie erwähnt',
  titleReply: '{sender} hat in {object} geantwortet',
  titleReplyOwn: '{sender} hat auf Ihre Nachricht geantwortet',
  titleMessage: 'Neue Nachricht in {object}',
  titleReaction: '{sender} hat mit {emoji} auf Ihre Nachricht reagiert',
  titleUpdate: '{object} wurde aktualisiert',
  titleCreate: '{object} wurde erstellt',
  titleAssignment: '{sender} hat Ihnen {object} zugewiesen',
  titleAssignmentNoSender: '{object} wurde Ihnen zugewiesen',
  titleRequest: 'Aktion erforderlich: {object}',
  quoteOwn: 'Ihre Nachricht',
  quoteOther: '{author} schrieb',
  quoteAnonymous: 'Ursprüngliche Nachricht',
  actionReply: 'In {app} antworten',
  actionOpen: 'In {app} öffnen',
  actionOpenObject: '{class} öffnen',
  readMore: 'Die vollständige Nachricht finden Sie in {app}',
  reasonMention: 'Sie erhalten diese E-Mail, weil Sie erwähnt wurden.',
  reasonConversation: 'Sie erhalten diese E-Mail, weil Sie diese Unterhaltung abonniert haben.',
  reasonObject: 'Sie erhalten diese E-Mail, weil Sie Aktualisierungen zu „{object}“ abonniert haben.',
  reasonAssignment: 'Sie erhalten diese E-Mail, weil Ihnen etwas zugewiesen wurde.',
  reasonRequest: 'Sie erhalten diese E-Mail, weil eine Aktion von Ihnen erforderlich ist.',
  reasonDefault: 'Sie erhalten diese E-Mail aufgrund Ihrer Benachrichtigungseinstellungen.',
  notificationSettings: 'Benachrichtigungseinstellungen',
  copyright: '© {app} — Alle Rechte vorbehalten'
}

const fr: EmailStrings = {
  eventMention: 'Vous avez été mentionné',
  eventReply: 'Nouvelle réponse',
  eventMessage: 'Nouveau message',
  eventReaction: 'Nouvelle réaction',
  eventUpdate: 'Mis à jour',
  eventCreate: 'Créé',
  eventAssignment: 'Vous a été assigné',
  eventRequest: 'Action requise',
  titleMention: '{sender} vous a mentionné',
  titleReply: '{sender} a répondu dans {object}',
  titleReplyOwn: '{sender} a répondu à votre message',
  titleMessage: 'Nouveau message dans {object}',
  titleReaction: '{sender} a réagi {emoji} à votre message',
  titleUpdate: '{object} a été mis à jour',
  titleCreate: '{object} a été créé',
  titleAssignment: '{sender} vous a assigné {object}',
  titleAssignmentNoSender: '{object} vous a été assigné',
  titleRequest: 'Action requise : {object}',
  quoteOwn: 'Votre message',
  quoteOther: '{author} a écrit',
  quoteAnonymous: 'Message d’origine',
  actionReply: 'Répondre dans {app}',
  actionOpen: 'Ouvrir dans {app}',
  actionOpenObject: 'Ouvrir : {class}',
  readMore: 'Lire le message complet dans {app}',
  reasonMention: 'Vous recevez cet e-mail parce que vous avez été mentionné.',
  reasonConversation: 'Vous recevez cet e-mail parce que vous suivez cette conversation.',
  reasonObject: 'Vous recevez cet e-mail parce que vous suivez les mises à jour de « {object} ».',
  reasonAssignment: 'Vous recevez cet e-mail parce que quelque chose vous a été assigné.',
  reasonRequest: 'Vous recevez cet e-mail parce qu’une action de votre part est requise.',
  reasonDefault: 'Vous recevez cet e-mail en raison de vos paramètres de notification.',
  notificationSettings: 'Paramètres de notification',
  copyright: '© {app} — Tous droits réservés'
}

const es: EmailStrings = {
  eventMention: 'Te han mencionado',
  eventReply: 'Nueva respuesta',
  eventMessage: 'Nuevo mensaje',
  eventReaction: 'Nueva reacción',
  eventUpdate: 'Actualizado',
  eventCreate: 'Creado',
  eventAssignment: 'Asignado a ti',
  eventRequest: 'Acción requerida',
  titleMention: '{sender} te ha mencionado',
  titleReply: '{sender} ha respondido en {object}',
  titleReplyOwn: '{sender} ha respondido a tu mensaje',
  titleMessage: 'Nuevo mensaje en {object}',
  titleReaction: '{sender} ha reaccionado con {emoji} a tu mensaje',
  titleUpdate: '{object} se ha actualizado',
  titleCreate: '{object} se ha creado',
  titleAssignment: '{sender} te ha asignado {object}',
  titleAssignmentNoSender: 'Se te ha asignado {object}',
  titleRequest: 'Acción requerida: {object}',
  quoteOwn: 'Tu mensaje',
  quoteOther: '{author} escribió',
  quoteAnonymous: 'Mensaje original',
  actionReply: 'Responder en {app}',
  actionOpen: 'Abrir en {app}',
  actionOpenObject: 'Abrir: {class}',
  readMore: 'Lee el mensaje completo en {app}',
  reasonMention: 'Recibes este correo porque te han mencionado.',
  reasonConversation: 'Recibes este correo porque sigues esta conversación.',
  reasonObject: 'Recibes este correo porque sigues las actualizaciones de «{object}».',
  reasonAssignment: 'Recibes este correo porque se te ha asignado algo.',
  reasonRequest: 'Recibes este correo porque se requiere una acción por tu parte.',
  reasonDefault: 'Recibes este correo según tu configuración de notificaciones.',
  notificationSettings: 'Configuración de notificaciones',
  copyright: '© {app} — Todos los derechos reservados'
}

const it: EmailStrings = {
  eventMention: 'Sei stato menzionato',
  eventReply: 'Nuova risposta',
  eventMessage: 'Nuovo messaggio',
  eventReaction: 'Nuova reazione',
  eventUpdate: 'Aggiornato',
  eventCreate: 'Creato',
  eventAssignment: 'Assegnato a te',
  eventRequest: 'Azione richiesta',
  titleMention: '{sender} ti ha menzionato',
  titleReply: '{sender} ha risposto in {object}',
  titleReplyOwn: '{sender} ha risposto al tuo messaggio',
  titleMessage: 'Nuovo messaggio in {object}',
  titleReaction: '{sender} ha reagito con {emoji} al tuo messaggio',
  titleUpdate: '{object} è stato aggiornato',
  titleCreate: '{object} è stato creato',
  titleAssignment: '{sender} ti ha assegnato {object}',
  titleAssignmentNoSender: '{object} ti è stato assegnato',
  titleRequest: 'Azione richiesta: {object}',
  quoteOwn: 'Il tuo messaggio',
  quoteOther: '{author} ha scritto',
  quoteAnonymous: 'Messaggio originale',
  actionReply: 'Rispondi in {app}',
  actionOpen: 'Apri in {app}',
  actionOpenObject: 'Apri: {class}',
  readMore: 'Leggi il messaggio completo in {app}',
  reasonMention: 'Ricevi questa email perché sei stato menzionato.',
  reasonConversation: 'Ricevi questa email perché segui questa conversazione.',
  reasonObject: 'Ricevi questa email perché segui gli aggiornamenti di «{object}».',
  reasonAssignment: 'Ricevi questa email perché ti è stato assegnato qualcosa.',
  reasonRequest: 'Ricevi questa email perché è richiesta una tua azione.',
  reasonDefault: 'Ricevi questa email in base alle tue impostazioni di notifica.',
  notificationSettings: 'Impostazioni di notifica',
  copyright: '© {app} — Tutti i diritti riservati'
}

const pt: EmailStrings = {
  eventMention: 'Foi mencionado',
  eventReply: 'Nova resposta',
  eventMessage: 'Nova mensagem',
  eventReaction: 'Nova reação',
  eventUpdate: 'Atualizado',
  eventCreate: 'Criado',
  eventAssignment: 'Atribuído a si',
  eventRequest: 'Ação necessária',
  titleMention: '{sender} mencionou-o',
  titleReply: '{sender} respondeu em {object}',
  titleReplyOwn: '{sender} respondeu à sua mensagem',
  titleMessage: 'Nova mensagem em {object}',
  titleReaction: '{sender} reagiu com {emoji} à sua mensagem',
  titleUpdate: '{object} foi atualizado',
  titleCreate: '{object} foi criado',
  titleAssignment: '{sender} atribuiu-lhe {object}',
  titleAssignmentNoSender: '{object} foi-lhe atribuído',
  titleRequest: 'Ação necessária: {object}',
  quoteOwn: 'A sua mensagem',
  quoteOther: '{author} escreveu',
  quoteAnonymous: 'Mensagem original',
  actionReply: 'Responder no {app}',
  actionOpen: 'Abrir no {app}',
  actionOpenObject: 'Abrir: {class}',
  readMore: 'Leia a mensagem completa no {app}',
  reasonMention: 'Está a receber este email porque foi mencionado.',
  reasonConversation: 'Está a receber este email porque segue esta conversa.',
  reasonObject: 'Está a receber este email porque segue as atualizações de «{object}».',
  reasonAssignment: 'Está a receber este email porque algo lhe foi atribuído.',
  reasonRequest: 'Está a receber este email porque é necessária uma ação sua.',
  reasonDefault: 'Está a receber este email de acordo com as suas definições de notificação.',
  notificationSettings: 'Definições de notificação',
  copyright: '© {app} — Todos os direitos reservados'
}

const ptBr: EmailStrings = {
  eventMention: 'Você foi mencionado',
  eventReply: 'Nova resposta',
  eventMessage: 'Nova mensagem',
  eventReaction: 'Nova reação',
  eventUpdate: 'Atualizado',
  eventCreate: 'Criado',
  eventAssignment: 'Atribuído a você',
  eventRequest: 'Ação necessária',
  titleMention: '{sender} mencionou você',
  titleReply: '{sender} respondeu em {object}',
  titleReplyOwn: '{sender} respondeu à sua mensagem',
  titleMessage: 'Nova mensagem em {object}',
  titleReaction: '{sender} reagiu com {emoji} à sua mensagem',
  titleUpdate: '{object} foi atualizado',
  titleCreate: '{object} foi criado',
  titleAssignment: '{sender} atribuiu {object} a você',
  titleAssignmentNoSender: '{object} foi atribuído a você',
  titleRequest: 'Ação necessária: {object}',
  quoteOwn: 'Sua mensagem',
  quoteOther: '{author} escreveu',
  quoteAnonymous: 'Mensagem original',
  actionReply: 'Responder no {app}',
  actionOpen: 'Abrir no {app}',
  actionOpenObject: 'Abrir: {class}',
  readMore: 'Leia a mensagem completa no {app}',
  reasonMention: 'Você está recebendo este e-mail porque foi mencionado.',
  reasonConversation: 'Você está recebendo este e-mail porque segue esta conversa.',
  reasonObject: 'Você está recebendo este e-mail porque segue as atualizações de “{object}”.',
  reasonAssignment: 'Você está recebendo este e-mail porque algo foi atribuído a você.',
  reasonRequest: 'Você está recebendo este e-mail porque uma ação sua é necessária.',
  reasonDefault: 'Você está recebendo este e-mail de acordo com suas configurações de notificação.',
  notificationSettings: 'Configurações de notificação',
  copyright: '© {app} — Todos os direitos reservados'
}

const cs: EmailStrings = {
  eventMention: 'Byli jste zmíněni',
  eventReply: 'Nová odpověď',
  eventMessage: 'Nová zpráva',
  eventReaction: 'Nová reakce',
  eventUpdate: 'Aktualizováno',
  eventCreate: 'Vytvořeno',
  eventAssignment: 'Přiřazeno vám',
  eventRequest: 'Vyžadována akce',
  titleMention: '{sender} vás zmínil(a)',
  titleReply: '{sender} odpověděl(a) v {object}',
  titleReplyOwn: '{sender} odpověděl(a) na vaši zprávu',
  titleMessage: 'Nová zpráva v {object}',
  titleReaction: '{sender} reagoval(a) {emoji} na vaši zprávu',
  titleUpdate: '{object}: aktualizováno',
  titleCreate: '{object}: vytvořeno',
  titleAssignment: '{sender} vám přiřadil(a) {object}',
  titleAssignmentNoSender: 'Bylo vám přiřazeno: {object}',
  titleRequest: 'Vyžadována akce: {object}',
  quoteOwn: 'Vaše zpráva',
  quoteOther: '{author} napsal(a)',
  quoteAnonymous: 'Původní zpráva',
  actionReply: 'Odpovědět v {app}',
  actionOpen: 'Otevřít v {app}',
  actionOpenObject: 'Otevřít: {class}',
  readMore: 'Celou zprávu najdete v {app}',
  reasonMention: 'Tento e-mail dostáváte, protože jste byli zmíněni.',
  reasonConversation: 'Tento e-mail dostáváte, protože sledujete tuto konverzaci.',
  reasonObject: 'Tento e-mail dostáváte, protože sledujete aktualizace „{object}“.',
  reasonAssignment: 'Tento e-mail dostáváte, protože vám bylo něco přiřazeno.',
  reasonRequest: 'Tento e-mail dostáváte, protože je vyžadována vaše akce.',
  reasonDefault: 'Tento e-mail dostáváte podle svého nastavení oznámení.',
  notificationSettings: 'Nastavení oznámení',
  copyright: '© {app} — Všechna práva vyhrazena'
}

const pl: EmailStrings = {
  eventMention: 'Wspomniano o Tobie',
  eventReply: 'Nowa odpowiedź',
  eventMessage: 'Nowa wiadomość',
  eventReaction: 'Nowa reakcja',
  eventUpdate: 'Zaktualizowano',
  eventCreate: 'Utworzono',
  eventAssignment: 'Przypisano do Ciebie',
  eventRequest: 'Wymagane działanie',
  titleMention: '{sender} wspomniał(a) o Tobie',
  titleReply: '{sender} odpowiedział(a) w {object}',
  titleReplyOwn: '{sender} odpowiedział(a) na Twoją wiadomość',
  titleMessage: 'Nowa wiadomość w {object}',
  titleReaction: '{sender} zareagował(a) {emoji} na Twoją wiadomość',
  titleUpdate: '{object}: zaktualizowano',
  titleCreate: '{object}: utworzono',
  titleAssignment: '{sender} przypisał(a) Ci {object}',
  titleAssignmentNoSender: 'Przypisano Ci: {object}',
  titleRequest: 'Wymagane działanie: {object}',
  quoteOwn: 'Twoja wiadomość',
  quoteOther: '{author} napisał(a)',
  quoteAnonymous: 'Oryginalna wiadomość',
  actionReply: 'Odpowiedz w {app}',
  actionOpen: 'Otwórz w {app}',
  actionOpenObject: 'Otwórz: {class}',
  readMore: 'Pełną wiadomość przeczytasz w {app}',
  reasonMention: 'Otrzymujesz tę wiadomość, ponieważ o Tobie wspomniano.',
  reasonConversation: 'Otrzymujesz tę wiadomość, ponieważ obserwujesz tę rozmowę.',
  reasonObject: 'Otrzymujesz tę wiadomość, ponieważ obserwujesz aktualizacje „{object}”.',
  reasonAssignment: 'Otrzymujesz tę wiadomość, ponieważ coś zostało Ci przypisane.',
  reasonRequest: 'Otrzymujesz tę wiadomość, ponieważ wymagane jest Twoje działanie.',
  reasonDefault: 'Otrzymujesz tę wiadomość zgodnie z ustawieniami powiadomień.',
  notificationSettings: 'Ustawienia powiadomień',
  copyright: '© {app} — Wszystkie prawa zastrzeżone'
}

const tr: EmailStrings = {
  eventMention: 'Sizden bahsedildi',
  eventReply: 'Yeni yanıt',
  eventMessage: 'Yeni mesaj',
  eventReaction: 'Yeni tepki',
  eventUpdate: 'Güncellendi',
  eventCreate: 'Oluşturuldu',
  eventAssignment: 'Size atandı',
  eventRequest: 'İşlem gerekli',
  titleMention: '{sender} sizden bahsetti',
  titleReply: '{sender} şurada yanıt verdi: {object}',
  titleReplyOwn: '{sender} mesajınıza yanıt verdi',
  titleMessage: 'Yeni mesaj: {object}',
  titleReaction: '{sender} mesajınıza {emoji} ile tepki verdi',
  titleUpdate: '{object} güncellendi',
  titleCreate: '{object} oluşturuldu',
  titleAssignment: '{sender} size şunu atadı: {object}',
  titleAssignmentNoSender: 'Size atandı: {object}',
  titleRequest: 'İşlem gerekli: {object}',
  quoteOwn: 'Mesajınız',
  quoteOther: '{author} yazdı',
  quoteAnonymous: 'Orijinal mesaj',
  actionReply: '{app} içinde yanıtla',
  actionOpen: '{app} içinde aç',
  actionOpenObject: 'Aç: {class}',
  readMore: 'Mesajın tamamını {app} içinde okuyun',
  reasonMention: 'Bu e-postayı sizden bahsedildiği için alıyorsunuz.',
  reasonConversation: 'Bu e-postayı bu konuşmayı takip ettiğiniz için alıyorsunuz.',
  reasonObject: 'Bu e-postayı “{object}” güncellemelerini takip ettiğiniz için alıyorsunuz.',
  reasonAssignment: 'Bu e-postayı size bir şey atandığı için alıyorsunuz.',
  reasonRequest: 'Bu e-postayı sizden bir işlem beklendiği için alıyorsunuz.',
  reasonDefault: 'Bu e-postayı bildirim ayarlarınız nedeniyle alıyorsunuz.',
  notificationSettings: 'Bildirim ayarları',
  copyright: '© {app} — Tüm hakları saklıdır'
}

const zh: EmailStrings = {
  eventMention: '有人提到了您',
  eventReply: '新回复',
  eventMessage: '新消息',
  eventReaction: '新回应',
  eventUpdate: '已更新',
  eventCreate: '已创建',
  eventAssignment: '已分配给您',
  eventRequest: '需要您处理',
  titleMention: '{sender} 提到了您',
  titleReply: '{sender} 在 {object} 中回复了',
  titleReplyOwn: '{sender} 回复了您的消息',
  titleMessage: '{object} 中有新消息',
  titleReaction: '{sender} 用 {emoji} 回应了您的消息',
  titleUpdate: '{object} 已更新',
  titleCreate: '{object} 已创建',
  titleAssignment: '{sender} 将 {object} 分配给了您',
  titleAssignmentNoSender: '{object} 已分配给您',
  titleRequest: '需要您处理：{object}',
  quoteOwn: '您的消息',
  quoteOther: '{author} 写道',
  quoteAnonymous: '原始消息',
  actionReply: '在 {app} 中回复',
  actionOpen: '在 {app} 中打开',
  actionOpenObject: '打开：{class}',
  readMore: '在 {app} 中阅读完整消息',
  reasonMention: '您收到此邮件是因为有人提到了您。',
  reasonConversation: '您收到此邮件是因为您关注了此对话。',
  reasonObject: '您收到此邮件是因为您关注了“{object}”的更新。',
  reasonAssignment: '您收到此邮件是因为有内容分配给了您。',
  reasonRequest: '您收到此邮件是因为需要您进行操作。',
  reasonDefault: '您收到此邮件是因为您的通知设置。',
  notificationSettings: '通知设置',
  copyright: '© {app} — 保留所有权利'
}

const ja: EmailStrings = {
  eventMention: 'メンションされました',
  eventReply: '新しい返信',
  eventMessage: '新しいメッセージ',
  eventReaction: '新しいリアクション',
  eventUpdate: '更新されました',
  eventCreate: '作成されました',
  eventAssignment: 'あなたに割り当てられました',
  eventRequest: '対応が必要です',
  titleMention: '{sender} さんがあなたをメンションしました',
  titleReply: '{sender} さんが {object} で返信しました',
  titleReplyOwn: '{sender} さんがあなたのメッセージに返信しました',
  titleMessage: '{object} に新しいメッセージがあります',
  titleReaction: '{sender} さんがあなたのメッセージに {emoji} でリアクションしました',
  titleUpdate: '{object} が更新されました',
  titleCreate: '{object} が作成されました',
  titleAssignment: '{sender} さんが {object} をあなたに割り当てました',
  titleAssignmentNoSender: '{object} があなたに割り当てられました',
  titleRequest: '対応が必要です: {object}',
  quoteOwn: 'あなたのメッセージ',
  quoteOther: '{author} さんのメッセージ',
  quoteAnonymous: '元のメッセージ',
  actionReply: '{app} で返信',
  actionOpen: '{app} で開く',
  actionOpenObject: '開く: {class}',
  readMore: 'メッセージの全文は {app} で確認できます',
  reasonMention: 'メンションされたため、このメールをお送りしています。',
  reasonConversation: 'この会話をフォローしているため、このメールをお送りしています。',
  reasonObject: '「{object}」の更新をフォローしているため、このメールをお送りしています。',
  reasonAssignment: 'あなたに割り当てられたため、このメールをお送りしています。',
  reasonRequest: 'あなたの対応が必要なため、このメールをお送りしています。',
  reasonDefault: '通知設定に基づいてこのメールをお送りしています。',
  notificationSettings: '通知設定',
  copyright: '© {app} — 無断転載を禁じます'
}

const ko: EmailStrings = {
  eventMention: '회원님이 언급되었습니다',
  eventReply: '새 답글',
  eventMessage: '새 메시지',
  eventReaction: '새 반응',
  eventUpdate: '업데이트됨',
  eventCreate: '생성됨',
  eventAssignment: '회원님에게 할당됨',
  eventRequest: '조치 필요',
  titleMention: '{sender}님이 회원님을 언급했습니다',
  titleReply: '{sender}님이 {object}에 답글을 남겼습니다',
  titleReplyOwn: '{sender}님이 회원님의 메시지에 답글을 남겼습니다',
  titleMessage: '{object}의 새 메시지',
  titleReaction: '{sender}님이 회원님의 메시지에 {emoji} 반응을 남겼습니다',
  titleUpdate: '{object}이(가) 업데이트되었습니다',
  titleCreate: '{object}이(가) 생성되었습니다',
  titleAssignment: '{sender}님이 {object}을(를) 회원님에게 할당했습니다',
  titleAssignmentNoSender: '{object}이(가) 회원님에게 할당되었습니다',
  titleRequest: '조치 필요: {object}',
  quoteOwn: '회원님의 메시지',
  quoteOther: '{author}님의 메시지',
  quoteAnonymous: '원본 메시지',
  actionReply: '{app}에서 답글 달기',
  actionOpen: '{app}에서 열기',
  actionOpenObject: '열기: {class}',
  readMore: '{app}에서 전체 메시지 읽기',
  reasonMention: '회원님이 언급되어 이 이메일을 보내 드립니다.',
  reasonConversation: '이 대화를 구독 중이어서 이 이메일을 보내 드립니다.',
  reasonObject: '“{object}”의 업데이트를 구독 중이어서 이 이메일을 보내 드립니다.',
  reasonAssignment: '회원님에게 할당된 항목이 있어 이 이메일을 보내 드립니다.',
  reasonRequest: '회원님의 조치가 필요하여 이 이메일을 보내 드립니다.',
  reasonDefault: '알림 설정에 따라 이 이메일을 보내 드립니다.',
  notificationSettings: '알림 설정',
  copyright: '© {app} — 모든 권리 보유'
}

/**
 * Email wording by language code.
 * @public
 */
export const emailStrings: Record<string, EmailStrings> = {
  en: defaultEmailStrings,
  ru,
  de,
  fr,
  es,
  it,
  pt,
  'pt-br': ptBr,
  cs,
  pl,
  tr,
  zh,
  ja,
  ko
}

/**
 * Wording for a language: exact code ("pt-br"), then its base ("pt"), then English.
 * @public
 */
export function getEmailStrings (lang?: string): EmailStrings {
  const code = (lang ?? 'en').toLowerCase().replace('_', '-')
  return emailStrings[code] ?? emailStrings[code.split('-')[0]] ?? defaultEmailStrings
}
