//
// Copyright © 2026 TraceX SAS.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Email wording per language. Kept in code rather than in plugin lang files because the
// transactor registers only English strings for platform plugins.

import { defaultEmailStrings, type EmailStrings } from './content'

const ru: EmailStrings = {
  titleMention: '{sender} упомянул(а) вас в {object}',
  titleReply: '{sender} ответил(а) в {object}',
  titleReplyOwn: '{sender} ответил(а) на ваше сообщение в {object}',
  titleMessage: 'Новое сообщение в {object}',
  titleReaction: '{sender} отреагировал(а) {emoji} на ваше сообщение в {object}',
  titleUpdate: '{object}: есть изменения',
  titleCreate: '{object}: создано',
  titleAssignment: '{sender} назначил(а) вам {object}',
  titleAssignmentNoSender: 'Вам назначено: {object}',
  titleCoAuthor: '{sender} добавил(а) вас в соавторы {object}',
  titleCoAuthorNoSender: 'Вас добавили в соавторы {object}',
  titleRequest: 'Требуется действие: {object}',
  quoteOwn: 'Ваше сообщение',
  quoteOther: '{author} пишет',
  quoteAnonymous: 'Исходное сообщение',
  actionReply: 'Ответить в {app}',
  actionOpen: 'Открыть в {app}',
  readMore: 'Полный текст сообщения — в {app}',
  reasonMention: 'Вы получили это письмо, потому что вас упомянули.',
  reasonConversation: 'Вы получили это письмо, потому что подписаны на это обсуждение.',
  reasonObject: 'Вы получили это письмо, потому что подписаны на обновления «{object}».',
  reasonAssignment: 'Вы получили это письмо, потому что вас назначили.',
  reasonCoAuthor: 'Вы получили это письмо, потому что вас добавили в соавторы.',
  reasonReaction: 'Вы получили это письмо, потому что кто-то отреагировал на ваше сообщение.',
  reasonRequest: 'Вы получили это письмо, потому что от вас ожидается действие.',
  reasonDefault: 'Вы получили это письмо в соответствии с настройками уведомлений.',
  notificationSettings: 'Настройки уведомлений',
  copyright: '© {app} — Все права защищены'
}

const de: EmailStrings = {
  titleMention: '{sender} hat Sie in {object} erwähnt',
  titleReply: '{sender} hat in {object} geantwortet',
  titleReplyOwn: '{sender} hat in {object} auf Ihre Nachricht geantwortet',
  titleMessage: 'Neue Nachricht in {object}',
  titleReaction: '{sender} hat in {object} mit {emoji} auf Ihre Nachricht reagiert',
  titleUpdate: '{object} wurde aktualisiert',
  titleCreate: '{object} wurde erstellt',
  titleAssignment: '{sender} hat Ihnen {object} zugewiesen',
  titleAssignmentNoSender: '{object} wurde Ihnen zugewiesen',
  titleCoAuthor: '{sender} hat Sie als Mitautor von {object} hinzugefügt',
  titleCoAuthorNoSender: 'Sie wurden als Mitautor von {object} hinzugefügt',
  titleRequest: 'Aktion erforderlich: {object}',
  quoteOwn: 'Ihre Nachricht',
  quoteOther: '{author} schrieb',
  quoteAnonymous: 'Ursprüngliche Nachricht',
  actionReply: 'In {app} antworten',
  actionOpen: 'In {app} öffnen',
  readMore: 'Die vollständige Nachricht finden Sie in {app}',
  reasonMention: 'Sie erhalten diese E-Mail, weil Sie erwähnt wurden.',
  reasonConversation: 'Sie erhalten diese E-Mail, weil Sie diese Unterhaltung abonniert haben.',
  reasonObject: 'Sie erhalten diese E-Mail, weil Sie Aktualisierungen zu „{object}“ abonniert haben.',
  reasonAssignment: 'Sie erhalten diese E-Mail, weil Ihnen etwas zugewiesen wurde.',
  reasonCoAuthor: 'Sie erhalten diese E-Mail, weil Sie als Mitautor hinzugefügt wurden.',
  reasonReaction: 'Sie erhalten diese E-Mail, weil jemand auf Ihre Nachricht reagiert hat.',
  reasonRequest: 'Sie erhalten diese E-Mail, weil eine Aktion von Ihnen erforderlich ist.',
  reasonDefault: 'Sie erhalten diese E-Mail aufgrund Ihrer Benachrichtigungseinstellungen.',
  notificationSettings: 'Benachrichtigungseinstellungen',
  copyright: '© {app} — Alle Rechte vorbehalten'
}

const fr: EmailStrings = {
  titleMention: '{sender} vous a mentionné dans {object}',
  titleReply: '{sender} a répondu dans {object}',
  titleReplyOwn: '{sender} a répondu à votre message dans {object}',
  titleMessage: 'Nouveau message dans {object}',
  titleReaction: '{sender} a réagi {emoji} à votre message dans {object}',
  titleUpdate: '{object} a été mis à jour',
  titleCreate: '{object} a été créé',
  titleAssignment: '{sender} vous a assigné {object}',
  titleAssignmentNoSender: '{object} vous a été assigné',
  titleCoAuthor: '{sender} vous a ajouté comme co-auteur de {object}',
  titleCoAuthorNoSender: 'Vous avez été ajouté comme co-auteur de {object}',
  titleRequest: 'Action requise : {object}',
  quoteOwn: 'Votre message',
  quoteOther: '{author} a écrit',
  quoteAnonymous: 'Message d’origine',
  actionReply: 'Répondre dans {app}',
  actionOpen: 'Ouvrir dans {app}',
  readMore: 'Lire le message complet dans {app}',
  reasonMention: 'Vous recevez cet e-mail parce que vous avez été mentionné.',
  reasonConversation: 'Vous recevez cet e-mail parce que vous suivez cette conversation.',
  reasonObject: 'Vous recevez cet e-mail parce que vous suivez les mises à jour de « {object} ».',
  reasonAssignment: 'Vous recevez cet e-mail parce que quelque chose vous a été assigné.',
  reasonCoAuthor: 'Vous recevez cet e-mail parce que vous avez été ajouté comme co-auteur.',
  reasonReaction: 'Vous recevez cet e-mail parce que quelqu’un a réagi à votre message.',
  reasonRequest: 'Vous recevez cet e-mail parce qu’une action de votre part est requise.',
  reasonDefault: 'Vous recevez cet e-mail en raison de vos paramètres de notification.',
  notificationSettings: 'Paramètres de notification',
  copyright: '© {app} — Tous droits réservés'
}

const es: EmailStrings = {
  titleMention: '{sender} te ha mencionado en {object}',
  titleReply: '{sender} ha respondido en {object}',
  titleReplyOwn: '{sender} ha respondido a tu mensaje en {object}',
  titleMessage: 'Nuevo mensaje en {object}',
  titleReaction: '{sender} ha reaccionado con {emoji} a tu mensaje en {object}',
  titleUpdate: '{object} se ha actualizado',
  titleCreate: '{object} se ha creado',
  titleAssignment: '{sender} te ha asignado {object}',
  titleAssignmentNoSender: 'Se te ha asignado {object}',
  titleCoAuthor: '{sender} te ha añadido como coautor de {object}',
  titleCoAuthorNoSender: 'Se te ha añadido como coautor de {object}',
  titleRequest: 'Acción requerida: {object}',
  quoteOwn: 'Tu mensaje',
  quoteOther: '{author} escribió',
  quoteAnonymous: 'Mensaje original',
  actionReply: 'Responder en {app}',
  actionOpen: 'Abrir en {app}',
  readMore: 'Lee el mensaje completo en {app}',
  reasonMention: 'Recibes este correo porque te han mencionado.',
  reasonConversation: 'Recibes este correo porque sigues esta conversación.',
  reasonObject: 'Recibes este correo porque sigues las actualizaciones de «{object}».',
  reasonAssignment: 'Recibes este correo porque se te ha asignado algo.',
  reasonCoAuthor: 'Recibes este correo porque se te ha añadido como coautor.',
  reasonReaction: 'Recibes este correo porque alguien ha reaccionado a tu mensaje.',
  reasonRequest: 'Recibes este correo porque se requiere una acción por tu parte.',
  reasonDefault: 'Recibes este correo según tu configuración de notificaciones.',
  notificationSettings: 'Configuración de notificaciones',
  copyright: '© {app} — Todos los derechos reservados'
}

const it: EmailStrings = {
  titleMention: '{sender} ti ha menzionato in {object}',
  titleReply: '{sender} ha risposto in {object}',
  titleReplyOwn: '{sender} ha risposto al tuo messaggio in {object}',
  titleMessage: 'Nuovo messaggio in {object}',
  titleReaction: '{sender} ha reagito con {emoji} al tuo messaggio in {object}',
  titleUpdate: '{object} è stato aggiornato',
  titleCreate: '{object} è stato creato',
  titleAssignment: '{sender} ti ha assegnato {object}',
  titleAssignmentNoSender: '{object} ti è stato assegnato',
  titleCoAuthor: '{sender} ti ha aggiunto come coautore di {object}',
  titleCoAuthorNoSender: 'Sei stato aggiunto come coautore di {object}',
  titleRequest: 'Azione richiesta: {object}',
  quoteOwn: 'Il tuo messaggio',
  quoteOther: '{author} ha scritto',
  quoteAnonymous: 'Messaggio originale',
  actionReply: 'Rispondi in {app}',
  actionOpen: 'Apri in {app}',
  readMore: 'Leggi il messaggio completo in {app}',
  reasonMention: 'Ricevi questa email perché sei stato menzionato.',
  reasonConversation: 'Ricevi questa email perché segui questa conversazione.',
  reasonObject: 'Ricevi questa email perché segui gli aggiornamenti di «{object}».',
  reasonAssignment: 'Ricevi questa email perché ti è stato assegnato qualcosa.',
  reasonCoAuthor: 'Ricevi questa email perché sei stato aggiunto come coautore.',
  reasonReaction: 'Ricevi questa email perché qualcuno ha reagito al tuo messaggio.',
  reasonRequest: 'Ricevi questa email perché è richiesta una tua azione.',
  reasonDefault: 'Ricevi questa email in base alle tue impostazioni di notifica.',
  notificationSettings: 'Impostazioni di notifica',
  copyright: '© {app} — Tutti i diritti riservati'
}

const pt: EmailStrings = {
  titleMention: '{sender} mencionou-o em {object}',
  titleReply: '{sender} respondeu em {object}',
  titleReplyOwn: '{sender} respondeu à sua mensagem em {object}',
  titleMessage: 'Nova mensagem em {object}',
  titleReaction: '{sender} reagiu com {emoji} à sua mensagem em {object}',
  titleUpdate: '{object} foi atualizado',
  titleCreate: '{object} foi criado',
  titleAssignment: '{sender} atribuiu-lhe {object}',
  titleAssignmentNoSender: '{object} foi-lhe atribuído',
  titleCoAuthor: '{sender} adicionou-o como coautor de {object}',
  titleCoAuthorNoSender: 'Foi adicionado como coautor de {object}',
  titleRequest: 'Ação necessária: {object}',
  quoteOwn: 'A sua mensagem',
  quoteOther: '{author} escreveu',
  quoteAnonymous: 'Mensagem original',
  actionReply: 'Responder no {app}',
  actionOpen: 'Abrir no {app}',
  readMore: 'Leia a mensagem completa no {app}',
  reasonMention: 'Está a receber este email porque foi mencionado.',
  reasonConversation: 'Está a receber este email porque segue esta conversa.',
  reasonObject: 'Está a receber este email porque segue as atualizações de «{object}».',
  reasonAssignment: 'Está a receber este email porque algo lhe foi atribuído.',
  reasonCoAuthor: 'Está a receber este email porque foi adicionado como coautor.',
  reasonReaction: 'Está a receber este email porque alguém reagiu à sua mensagem.',
  reasonRequest: 'Está a receber este email porque é necessária uma ação sua.',
  reasonDefault: 'Está a receber este email de acordo com as suas definições de notificação.',
  notificationSettings: 'Definições de notificação',
  copyright: '© {app} — Todos os direitos reservados'
}

const ptBr: EmailStrings = {
  titleMention: '{sender} mencionou você em {object}',
  titleReply: '{sender} respondeu em {object}',
  titleReplyOwn: '{sender} respondeu à sua mensagem em {object}',
  titleMessage: 'Nova mensagem em {object}',
  titleReaction: '{sender} reagiu com {emoji} à sua mensagem em {object}',
  titleUpdate: '{object} foi atualizado',
  titleCreate: '{object} foi criado',
  titleAssignment: '{sender} atribuiu {object} a você',
  titleAssignmentNoSender: '{object} foi atribuído a você',
  titleCoAuthor: '{sender} adicionou você como coautor de {object}',
  titleCoAuthorNoSender: 'Você foi adicionado como coautor de {object}',
  titleRequest: 'Ação necessária: {object}',
  quoteOwn: 'Sua mensagem',
  quoteOther: '{author} escreveu',
  quoteAnonymous: 'Mensagem original',
  actionReply: 'Responder no {app}',
  actionOpen: 'Abrir no {app}',
  readMore: 'Leia a mensagem completa no {app}',
  reasonMention: 'Você está recebendo este e-mail porque foi mencionado.',
  reasonConversation: 'Você está recebendo este e-mail porque segue esta conversa.',
  reasonObject: 'Você está recebendo este e-mail porque segue as atualizações de “{object}”.',
  reasonAssignment: 'Você está recebendo este e-mail porque algo foi atribuído a você.',
  reasonCoAuthor: 'Você está recebendo este e-mail porque foi adicionado como coautor.',
  reasonReaction: 'Você está recebendo este e-mail porque alguém reagiu à sua mensagem.',
  reasonRequest: 'Você está recebendo este e-mail porque uma ação sua é necessária.',
  reasonDefault: 'Você está recebendo este e-mail de acordo com suas configurações de notificação.',
  notificationSettings: 'Configurações de notificação',
  copyright: '© {app} — Todos os direitos reservados'
}

const cs: EmailStrings = {
  titleMention: '{sender} vás zmínil(a) v {object}',
  titleReply: '{sender} odpověděl(a) v {object}',
  titleReplyOwn: '{sender} odpověděl(a) na vaši zprávu v {object}',
  titleMessage: 'Nová zpráva v {object}',
  titleReaction: '{sender} reagoval(a) {emoji} na vaši zprávu v {object}',
  titleUpdate: '{object}: aktualizováno',
  titleCreate: '{object}: vytvořeno',
  titleAssignment: '{sender} vám přiřadil(a) {object}',
  titleAssignmentNoSender: 'Bylo vám přiřazeno: {object}',
  titleCoAuthor: '{sender} vás přidal(a) jako spoluautora {object}',
  titleCoAuthorNoSender: 'Byli jste přidáni jako spoluautor {object}',
  titleRequest: 'Vyžadována akce: {object}',
  quoteOwn: 'Vaše zpráva',
  quoteOther: '{author} napsal(a)',
  quoteAnonymous: 'Původní zpráva',
  actionReply: 'Odpovědět v {app}',
  actionOpen: 'Otevřít v {app}',
  readMore: 'Celou zprávu najdete v {app}',
  reasonMention: 'Tento e-mail dostáváte, protože jste byli zmíněni.',
  reasonConversation: 'Tento e-mail dostáváte, protože sledujete tuto konverzaci.',
  reasonObject: 'Tento e-mail dostáváte, protože sledujete aktualizace „{object}“.',
  reasonAssignment: 'Tento e-mail dostáváte, protože vám bylo něco přiřazeno.',
  reasonCoAuthor: 'Tento e-mail dostáváte, protože jste byli přidáni jako spoluautor.',
  reasonReaction: 'Tento e-mail dostáváte, protože někdo reagoval na vaši zprávu.',
  reasonRequest: 'Tento e-mail dostáváte, protože je vyžadována vaše akce.',
  reasonDefault: 'Tento e-mail dostáváte podle svého nastavení oznámení.',
  notificationSettings: 'Nastavení oznámení',
  copyright: '© {app} — Všechna práva vyhrazena'
}

const pl: EmailStrings = {
  titleMention: '{sender} wspomniał(a) o Tobie w {object}',
  titleReply: '{sender} odpowiedział(a) w {object}',
  titleReplyOwn: '{sender} odpowiedział(a) na Twoją wiadomość w {object}',
  titleMessage: 'Nowa wiadomość w {object}',
  titleReaction: '{sender} zareagował(a) {emoji} na Twoją wiadomość w {object}',
  titleUpdate: '{object}: zaktualizowano',
  titleCreate: '{object}: utworzono',
  titleAssignment: '{sender} przypisał(a) Ci {object}',
  titleAssignmentNoSender: 'Przypisano Ci: {object}',
  titleCoAuthor: '{sender} dodał(a) Cię jako współautora {object}',
  titleCoAuthorNoSender: 'Dodano Cię jako współautora {object}',
  titleRequest: 'Wymagane działanie: {object}',
  quoteOwn: 'Twoja wiadomość',
  quoteOther: '{author} napisał(a)',
  quoteAnonymous: 'Oryginalna wiadomość',
  actionReply: 'Odpowiedz w {app}',
  actionOpen: 'Otwórz w {app}',
  readMore: 'Pełną wiadomość przeczytasz w {app}',
  reasonMention: 'Otrzymujesz tę wiadomość, ponieważ o Tobie wspomniano.',
  reasonConversation: 'Otrzymujesz tę wiadomość, ponieważ obserwujesz tę rozmowę.',
  reasonObject: 'Otrzymujesz tę wiadomość, ponieważ obserwujesz aktualizacje „{object}”.',
  reasonAssignment: 'Otrzymujesz tę wiadomość, ponieważ coś zostało Ci przypisane.',
  reasonCoAuthor: 'Otrzymujesz tę wiadomość, ponieważ dodano Cię jako współautora.',
  reasonReaction: 'Otrzymujesz tę wiadomość, ponieważ ktoś zareagował na Twoją wiadomość.',
  reasonRequest: 'Otrzymujesz tę wiadomość, ponieważ wymagane jest Twoje działanie.',
  reasonDefault: 'Otrzymujesz tę wiadomość zgodnie z ustawieniami powiadomień.',
  notificationSettings: 'Ustawienia powiadomień',
  copyright: '© {app} — Wszystkie prawa zastrzeżone'
}

const tr: EmailStrings = {
  titleMention: '{sender} sizden şurada bahsetti: {object}',
  titleReply: '{sender} şurada yanıt verdi: {object}',
  titleReplyOwn: '{sender} mesajınıza şurada yanıt verdi: {object}',
  titleMessage: 'Yeni mesaj: {object}',
  titleReaction: '{sender} mesajınıza {emoji} ile tepki verdi: {object}',
  titleUpdate: '{object} güncellendi',
  titleCreate: '{object} oluşturuldu',
  titleAssignment: '{sender} size şunu atadı: {object}',
  titleAssignmentNoSender: 'Size atandı: {object}',
  titleCoAuthor: '{sender} sizi şunun ortak yazarı olarak ekledi: {object}',
  titleCoAuthorNoSender: 'Şunun ortak yazarı olarak eklendiniz: {object}',
  titleRequest: 'İşlem gerekli: {object}',
  quoteOwn: 'Mesajınız',
  quoteOther: '{author} yazdı',
  quoteAnonymous: 'Orijinal mesaj',
  actionReply: '{app} içinde yanıtla',
  actionOpen: '{app} içinde aç',
  readMore: 'Mesajın tamamını {app} içinde okuyun',
  reasonMention: 'Bu e-postayı sizden bahsedildiği için alıyorsunuz.',
  reasonConversation: 'Bu e-postayı bu konuşmayı takip ettiğiniz için alıyorsunuz.',
  reasonObject: 'Bu e-postayı “{object}” güncellemelerini takip ettiğiniz için alıyorsunuz.',
  reasonAssignment: 'Bu e-postayı size bir şey atandığı için alıyorsunuz.',
  reasonCoAuthor: 'Bu e-postayı ortak yazar olarak eklendiğiniz için alıyorsunuz.',
  reasonReaction: 'Bu e-postayı biri mesajınıza tepki verdiği için alıyorsunuz.',
  reasonRequest: 'Bu e-postayı sizden bir işlem beklendiği için alıyorsunuz.',
  reasonDefault: 'Bu e-postayı bildirim ayarlarınız nedeniyle alıyorsunuz.',
  notificationSettings: 'Bildirim ayarları',
  copyright: '© {app} — Tüm hakları saklıdır'
}

const zh: EmailStrings = {
  titleMention: '{sender} 在 {object} 中提到了您',
  titleReply: '{sender} 在 {object} 中回复了',
  titleReplyOwn: '{sender} 在 {object} 中回复了您的消息',
  titleMessage: '{object} 中有新消息',
  titleReaction: '{sender} 在 {object} 中用 {emoji} 回应了您的消息',
  titleUpdate: '{object} 已更新',
  titleCreate: '{object} 已创建',
  titleAssignment: '{sender} 将 {object} 分配给了您',
  titleAssignmentNoSender: '{object} 已分配给您',
  titleCoAuthor: '{sender} 将您添加为 {object} 的合著者',
  titleCoAuthorNoSender: '您已被添加为 {object} 的合著者',
  titleRequest: '需要您处理：{object}',
  quoteOwn: '您的消息',
  quoteOther: '{author} 写道',
  quoteAnonymous: '原始消息',
  actionReply: '在 {app} 中回复',
  actionOpen: '在 {app} 中打开',
  readMore: '在 {app} 中阅读完整消息',
  reasonMention: '您收到此邮件是因为有人提到了您。',
  reasonConversation: '您收到此邮件是因为您关注了此对话。',
  reasonObject: '您收到此邮件是因为您关注了“{object}”的更新。',
  reasonAssignment: '您收到此邮件是因为有内容分配给了您。',
  reasonCoAuthor: '您收到此邮件是因为您被添加为合著者。',
  reasonReaction: '您收到此邮件是因为有人回应了您的消息。',
  reasonRequest: '您收到此邮件是因为需要您进行操作。',
  reasonDefault: '您收到此邮件是因为您的通知设置。',
  notificationSettings: '通知设置',
  copyright: '© {app} — 保留所有权利'
}

const ja: EmailStrings = {
  titleMention: '{sender} さんが {object} であなたをメンションしました',
  titleReply: '{sender} さんが {object} で返信しました',
  titleReplyOwn: '{sender} さんが {object} であなたのメッセージに返信しました',
  titleMessage: '{object} に新しいメッセージがあります',
  titleReaction: '{sender} さんが {object} であなたのメッセージに {emoji} でリアクションしました',
  titleUpdate: '{object} が更新されました',
  titleCreate: '{object} が作成されました',
  titleAssignment: '{sender} さんが {object} をあなたに割り当てました',
  titleAssignmentNoSender: '{object} があなたに割り当てられました',
  titleCoAuthor: '{sender} さんがあなたを {object} の共著者に追加しました',
  titleCoAuthorNoSender: 'あなたは {object} の共著者に追加されました',
  titleRequest: '対応が必要です: {object}',
  quoteOwn: 'あなたのメッセージ',
  quoteOther: '{author} さんのメッセージ',
  quoteAnonymous: '元のメッセージ',
  actionReply: '{app} で返信',
  actionOpen: '{app} で開く',
  readMore: 'メッセージの全文は {app} で確認できます',
  reasonMention: 'メンションされたため、このメールをお送りしています。',
  reasonConversation: 'この会話をフォローしているため、このメールをお送りしています。',
  reasonObject: '「{object}」の更新をフォローしているため、このメールをお送りしています。',
  reasonAssignment: 'あなたに割り当てられたため、このメールをお送りしています。',
  reasonCoAuthor: '共著者に追加されたため、このメールをお送りしています。',
  reasonReaction: 'あなたのメッセージにリアクションがあったため、このメールをお送りしています。',
  reasonRequest: 'あなたの対応が必要なため、このメールをお送りしています。',
  reasonDefault: '通知設定に基づいてこのメールをお送りしています。',
  notificationSettings: '通知設定',
  copyright: '© {app} — 無断転載を禁じます'
}

const ko: EmailStrings = {
  titleMention: '{sender}님이 {object}에서 회원님을 언급했습니다',
  titleReply: '{sender}님이 {object}에 답글을 남겼습니다',
  titleReplyOwn: '{sender}님이 {object}에서 회원님의 메시지에 답글을 남겼습니다',
  titleMessage: '{object}의 새 메시지',
  titleReaction: '{sender}님이 {object}에서 회원님의 메시지에 {emoji} 반응을 남겼습니다',
  titleUpdate: '{object}이(가) 업데이트되었습니다',
  titleCreate: '{object}이(가) 생성되었습니다',
  titleAssignment: '{sender}님이 {object}을(를) 회원님에게 할당했습니다',
  titleAssignmentNoSender: '{object}이(가) 회원님에게 할당되었습니다',
  titleCoAuthor: '{sender}님이 회원님을 {object}의 공동 작성자로 추가했습니다',
  titleCoAuthorNoSender: '회원님이 {object}의 공동 작성자로 추가되었습니다',
  titleRequest: '조치 필요: {object}',
  quoteOwn: '회원님의 메시지',
  quoteOther: '{author}님의 메시지',
  quoteAnonymous: '원본 메시지',
  actionReply: '{app}에서 답글 달기',
  actionOpen: '{app}에서 열기',
  readMore: '{app}에서 전체 메시지 읽기',
  reasonMention: '회원님이 언급되어 이 이메일을 보내 드립니다.',
  reasonConversation: '이 대화를 구독 중이어서 이 이메일을 보내 드립니다.',
  reasonObject: '“{object}”의 업데이트를 구독 중이어서 이 이메일을 보내 드립니다.',
  reasonAssignment: '회원님에게 할당된 항목이 있어 이 이메일을 보내 드립니다.',
  reasonCoAuthor: '공동 작성자로 추가되어 이 이메일을 보내 드립니다.',
  reasonReaction: '누군가 회원님의 메시지에 반응하여 이 이메일을 보내 드립니다.',
  reasonRequest: '회원님의 조치가 필요하여 이 이메일을 보내 드립니다.',
  reasonDefault: '알림 설정에 따라 이 이메일을 보내 드립니다.',
  notificationSettings: '알림 설정',
  copyright: '© {app} — 모든 권리 보유'
}

/**
 * Email wording by language code.
 * @public
 */
export const emailStrings: Record<string, EmailStrings> = {
  en: defaultEmailStrings,
  ru,
  de,
  fr,
  es,
  it,
  pt,
  'pt-br': ptBr,
  cs,
  pl,
  tr,
  zh,
  ja,
  ko
}

/**
 * Wording for a language: exact code ("pt-br"), then its base ("pt"), then English.
 * @public
 */
export function getEmailStrings (lang?: string): EmailStrings {
  const code = (lang ?? 'en').toLowerCase().replace('_', '-')
  return emailStrings[code] ?? emailStrings[code.split('-')[0]] ?? defaultEmailStrings
}
